"""ARM H frozen constants — GENERATED by gen_armh_constants.py from LIVE code.

DO NOT EDIT BY HAND. ARM G hand-transcribed 28 constants and ALL of them were wrong
by ~1e-5; it then hypothesised a BLAS batch-shape cause and measured it (refuted by
~10 orders) when the cause was its typing. `armh_assert_constants()` re-derives every
number here from live code at run start and REFUSES TO RUN on drift.
"""

from __future__ import annotations

ARMH_LAYOUT_REF = "flmpg-yuo,sntdcireahkxbwv'.jzq"   # arm B
ARMH_REF_MS = 253.90057910352604
ARMH_TARGET = "oxey-style"
ARMH_TOL = 1e-9
ARMH_BIG = 1e6
#: the 13 HARD-constrained axes = LIVE_GAUGES minus the target. sfr already excluded.
ARMH_CONSTRAINED = ('sfb', 'sfs', 'sfb-dist', 'sfs-dist', 'lsb', 'lsb-dist', 'alt', 'roll', 'sr-roll', 'redir', 'scissor', 'imbalance', 'comfort')
ARMH_LIVE = ('sfb', 'sfs', 'sfb-dist', 'sfs-dist', 'lsb', 'lsb-dist', 'alt', 'roll', 'sr-roll', 'redir', 'scissor', 'imbalance', 'oxey-style', 'comfort')
#: directions, DERIVED two ways (qwerty-is-worst 14/14; rank-corr 13/14).
ARMH_DIR = {
    'sfb': 1.0,
    'sfs': 1.0,
    'sfb-dist': 1.0,
    'sfs-dist': 1.0,
    'lsb': 1.0,
    'lsb-dist': 1.0,
    'alt': -1.0,
    'roll': -1.0,
    'sr-roll': -1.0,
    'redir': 1.0,
    'scissor': 1.0,
    'imbalance': 1.0,
    'oxey-style': 1.0,
    'comfort': 1.0,
}
#: arm B's gauge values — the CONSTRAINT LEVELS. Re-asserted at run start.
ARMH_REF = {
    'sfb': 2.539124615505356,
    'sfs': 6.799508454836403,
    'sfb-dist': 3.0423296718509323,
    'sfs-dist': 8.00562391148118,
    'lsb': 1.1410913569660872,
    'lsb-dist': 2.322675604674633,
    'alt': 37.13733008655502,
    'roll': 45.442097658599806,
    'sr-roll': 17.813072191285166,
    'redir': 4.420586814037255,
    'scissor': 0.25671106120493087,
    'imbalance': 4.8753996439391,
    'oxey-style': 8.611045585392063,
    'comfort': 3.4140465,
}
#: the six frozen SPEEDTIE-1 1M champions, read from the ORIGINAL artifact.
ARMH_SIX = (
    "flmpg-yuo,sntdcireahkxbwv'.jzq",
    "puy.,vdfnlheioamtsrc'jqk-gwbxz",
    "pyou,vdflrghaeictsnmk'j.-wbzxq",
    "lcfmk.uoyprnstdiaeghzxwbv-,'qj",
    "lnfdg.,yehcrstmaoiupxzbwvk-q'j",
    "pyu.,gdfnlhieaocstrmkj'-qbwzvx",
)
#: BALL-1: the ONE 13-axis-feasible member of arm B's exhaustive 1-swap ball.
#: A PREREG INPUT (frozen-geometry enumeration), not an ARM H search result.
ARMH_BALL1 = "flmpg-yuo,sntcdireahkxbwv'.jzq"
ARMH_BALL1_MS = 253.9664262616864
ARMH_BALL1_OXEY = 7.577429131770819
ARMH_FLIP_SD = 0.03292357908017607   # sd_H at which BALL-1 enters the band
ARMH_SEEDS = (31337, 136066, 240795, 345524, 450253)
ARMH_SEED_FORMULA = '31337 + 104729*r, r=0..4'
