"""GENERATE `armh_constants.py` from prereg-inputs.json + ball-probe.json.

The two inputs are themselves generated from LIVE code by `gen_prereg_inputs.py` and
`probe_ball.py`. Nothing in the chain is hand-typed. Re-run to regenerate; the run-time
`armh_assert_constants()` re-derives every value again and refuses to start on drift.
"""

from __future__ import annotations

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent


def main() -> int:
    b = json.load(open(HERE / "prereg-inputs.json"))
    bb = json.load(open(HERE / "ball-probe.json"))
    f = bb["feasible_in_1swap_ball"][0]
    L = ['"""ARM H frozen constants — GENERATED by gen_armh_constants.py from LIVE code.',
         "",
         "DO NOT EDIT BY HAND. ARM G hand-transcribed 28 constants and ALL of them were wrong",
         "by ~1e-5; it then hypothesised a BLAS batch-shape cause and measured it (refuted by",
         "~10 orders) when the cause was its typing. `armh_assert_constants()` re-derives every",
         "number here from live code at run start and REFUSES TO RUN on drift.",
         '"""', "", "from __future__ import annotations", ""]
    L.append(f"ARMH_LAYOUT_REF = {b['six_frozen_champions'][0]!r}   # arm B")
    L.append(f"ARMH_REF_MS = {b['armB_ms_rederived']!r}")
    L.append('ARMH_TARGET = "oxey-style"')
    L.append("ARMH_TOL = 1e-9")
    L.append("ARMH_BIG = 1e6")
    L.append("#: the 13 HARD-constrained axes = LIVE_GAUGES minus the target. sfr already excluded.")
    L.append(f"ARMH_CONSTRAINED = {tuple(b['constrained_axes'])!r}")
    L.append(f"ARMH_LIVE = {tuple(b['live_gauges'])!r}")
    L.append("#: directions, DERIVED two ways (qwerty-is-worst 14/14; rank-corr 13/14).")
    L.append("ARMH_DIR = {")
    for g in b["live_gauges"]:
        L.append(f"    {g!r}: {b['directions'][g]!r},")
    L.append("}")
    L.append("#: arm B's gauge values — the CONSTRAINT LEVELS. Re-asserted at run start.")
    L.append("ARMH_REF = {")
    for g in b["live_gauges"]:
        L.append(f"    {g!r}: {b['armB_gauges'][g]!r},")
    L.append("}")
    L.append("#: the six frozen SPEEDTIE-1 1M champions, read from the ORIGINAL artifact.")
    L.append("ARMH_SIX = (")
    for s in b["six_frozen_champions"]:
        L.append(f"    {s!r},")
    L.append(")")
    L.append("#: BALL-1: the ONE 13-axis-feasible member of arm B's exhaustive 1-swap ball.")
    L.append("#: A PREREG INPUT (frozen-geometry enumeration), not an ARM H search result.")
    L.append(f"ARMH_BALL1 = {f['layout']!r}")
    L.append(f"ARMH_BALL1_MS = {f['ms']!r}")
    L.append(f"ARMH_BALL1_OXEY = {f['oxey']!r}")
    L.append(f"ARMH_FLIP_SD = {f['ms_minus_armB'] / 2!r}   # sd_H at which BALL-1 enters the band")
    L.append(f"ARMH_SEEDS = {tuple(b['seeds']['values'])!r}")
    L.append(f"ARMH_SEED_FORMULA = {b['seeds']['formula']!r}")
    (HERE / "armh_constants.py").write_text("\n".join(L) + "\n")
    print(f"WROTE {HERE / 'armh_constants.py'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
