"""Mechanical mutation sweep of tests/analysis/test_bad_scissor.py against bad_scissor.py.

Run BEFORE reading the module: mutants are generated by AST rewriting, not by
comprehension, so this pass reports what the suite can defend without me having
formed any opinion about what it should defend.

Gate on the EXIT CODE, never on pytest prose (TOOLING-TRAPS: a case-sensitive grep on
"FAILED" made a prior harness report 24/24 SURVIVED). Positive-controlled via
keybo.testkit.assert_harness_detects_a_fatal_mutant before any verdict is trusted.

Usage:  PYTHONPATH=/tmp/bsaudit/src python mutation_sweep.py [--target FILE] [--tests FILE]
"""

from __future__ import annotations

import argparse
import ast
import json
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from keybo.testkit import assert_harness_detects_a_fatal_mutant, assert_module_under

ROOT = Path("/tmp/bsaudit")


@dataclass
class Mutant:
    kind: str
    lineno: int
    before: str
    after: str
    source: str = field(repr=False, default="")


class _Mutator(ast.NodeTransformer):
    """Applies exactly one mutation, identified by (node id, kind)."""

    def __init__(self, target_id: int, kind: str) -> None:
        self.target_id = target_id
        self.kind = kind
        self.applied = False

    def _hit(self, node: ast.AST) -> bool:
        return id(node) == self.target_id

    def visit_Compare(self, node: ast.Compare):  # noqa: N802
        self.generic_visit(node)
        if not self._hit(node):
            return node
        swaps = {
            ast.Eq: ast.NotEq, ast.NotEq: ast.Eq,
            ast.Lt: ast.GtE, ast.GtE: ast.Lt,
            ast.Gt: ast.LtE, ast.LtE: ast.Gt,
            ast.In: ast.NotIn, ast.NotIn: ast.In,
            ast.Is: ast.IsNot, ast.IsNot: ast.Is,
        }
        op = type(node.ops[0])
        if self.kind == "cmp" and op in swaps:
            node.ops = [swaps[op]()]
            self.applied = True
        return node

    def visit_BoolOp(self, node: ast.BoolOp):  # noqa: N802
        self.generic_visit(node)
        if not self._hit(node):
            return node
        if self.kind == "boolop":
            node.op = ast.Or() if isinstance(node.op, ast.And) else ast.And()
            self.applied = True
        return node

    def visit_UnaryOp(self, node: ast.UnaryOp):  # noqa: N802
        self.generic_visit(node)
        if not self._hit(node):
            return node
        if self.kind == "drop_not" and isinstance(node.op, ast.Not):
            self.applied = True
            return node.operand
        return node

    def visit_BinOp(self, node: ast.BinOp):  # noqa: N802
        self.generic_visit(node)
        if not self._hit(node):
            return node
        swaps = {
            ast.Add: ast.Sub, ast.Sub: ast.Add,
            ast.Mult: ast.Div, ast.Div: ast.Mult,
        }
        op = type(node.op)
        if self.kind == "binop" and op in swaps:
            node.op = swaps[op]()
            self.applied = True
        return node

    def visit_Constant(self, node: ast.Constant):  # noqa: N802
        if not self._hit(node):
            return node
        if self.kind == "const":
            v = node.value
            if isinstance(v, bool):
                node.value = not v
            elif isinstance(v, int):
                node.value = v + 1
            elif isinstance(v, float):
                node.value = v + 1.0
            elif isinstance(v, str):
                node.value = v + "X"
            else:
                return node
            self.applied = True
        return node

    def visit_Return(self, node: ast.Return):  # noqa: N802
        self.generic_visit(node)
        if not self._hit(node):
            return node
        if self.kind == "swap_args":
            self.applied = True
        return node


def _swap_call_args(tree: ast.AST, target_id: int) -> bool:
    """Swap the last two positional args of one call — catches a/b order confusion."""
    for n in ast.walk(tree):
        if isinstance(n, ast.Call) and id(n) == target_id and len(n.args) >= 2:
            n.args[-1], n.args[-2] = n.args[-2], n.args[-1]
            return True
    return False


def enumerate_mutants(src: str) -> list[Mutant]:
    """Every single-point mutant the AST admits, in source order."""
    out: list[Mutant] = []
    base = ast.parse(src)
    # Node identities are unstable across parses, so re-parse per candidate and index
    # by (kind, position-in-walk-order) which IS stable for a fixed source string.
    kinds: list[tuple[str, int]] = []
    for i, n in enumerate(ast.walk(base)):
        if isinstance(n, ast.Compare):
            kinds.append(("cmp", i))
        elif isinstance(n, ast.BoolOp):
            kinds.append(("boolop", i))
        elif isinstance(n, ast.UnaryOp) and isinstance(n.op, ast.Not):
            kinds.append(("drop_not", i))
        elif isinstance(n, ast.BinOp) and type(n.op) in (ast.Add, ast.Sub, ast.Mult, ast.Div):
            kinds.append(("binop", i))
        elif isinstance(n, ast.Constant) and isinstance(n.value, (bool, int, float, str)):
            # Skip docstrings: mutating prose is not a behaviour mutant.
            kinds.append(("const", i))
        elif isinstance(n, ast.Call) and len(n.args) >= 2:
            kinds.append(("swap_args", i))

    docstring_ids = set()
    for n in ast.walk(base):
        if isinstance(n, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if n.body and isinstance(n.body[0], ast.Expr) and isinstance(n.body[0].value, ast.Constant):
                docstring_ids.add(id(n.body[0].value))
    doc_positions = {i for i, n in enumerate(ast.walk(base)) if id(n) in docstring_ids}

    for kind, pos in kinds:
        if kind == "const" and pos in doc_positions:
            continue
        tree = ast.parse(src)
        nodes = list(ast.walk(tree))
        node = nodes[pos]
        before = ast.unparse(node)
        lineno = getattr(node, "lineno", 0)
        if kind == "swap_args":
            ok = _swap_call_args(tree, id(node))
            if not ok:
                continue
        else:
            m = _Mutator(id(node), kind)
            tree = m.visit(tree)
            if not m.applied:
                continue
        ast.fix_missing_locations(tree)
        mutated_src = ast.unparse(tree)
        if mutated_src == ast.unparse(ast.parse(src)):
            continue  # no-op mutant
        # Recover the mutated node's text for the report.
        after_nodes = list(ast.walk(tree))
        after = ast.unparse(after_nodes[pos]) if pos < len(after_nodes) else "<n/a>"
        out.append(Mutant(kind=kind, lineno=lineno, before=before, after=after, source=mutated_src))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", default="src/keybo/analysis/bad_scissor.py")
    ap.add_argument("--tests", default="tests/analysis/test_bad_scissor.py")
    ap.add_argument("--full-suite", action="store_true",
                    help="run the WHOLE suite per mutant, not just --tests")
    ap.add_argument("--out", default="agent-artifacts/bsaudit/mutation_sweep.json")
    args = ap.parse_args()

    assert_module_under("keybo", ROOT)
    target = ROOT / args.target
    tests = ROOT / args.tests
    original = target.read_text()

    def run_suite() -> int:
        cmd = [sys.executable, "-m", "pytest", "-q", "-x", "--no-header", "-p", "no:cacheprovider"]
        cmd += [str(tests)] if not args.full_suite else []
        return subprocess.run(cmd, cwd=ROOT, capture_output=True).returncode

    def apply_fatal() -> None:
        # A mutant the suite MUST catch if it tests anything at all: make the
        # top-level predicate constant-False.
        tree = ast.parse(original)
        for n in ast.walk(tree):
            if isinstance(n, ast.FunctionDef) and n.name == "bad_scissor":
                doc = n.body[0] if isinstance(n.body[0], ast.Expr) else None
                n.body = ([doc] if doc else []) + [ast.Return(value=ast.Constant(value=False))]
        ast.fix_missing_locations(tree)
        target.write_text(ast.unparse(tree))

    def restore() -> None:
        target.write_text(original)

    print("=== POSITIVE CONTROL (runs BEFORE any verdict is trusted) ===", flush=True)
    assert_harness_detects_a_fatal_mutant(run_suite, apply_fatal, restore)
    print("PASS: baseline green, fatal mutant CAUGHT by exit code, restore returned green\n", flush=True)

    mutants = enumerate_mutants(original)
    print(f"=== SWEEP: {len(mutants)} mechanically-generated mutants ===", flush=True)
    results = []
    try:
        for i, m in enumerate(mutants, 1):
            target.write_text(m.source)
            rc = run_suite()
            verdict = "CAUGHT" if rc != 0 else "SURVIVED"
            results.append({
                "n": i, "kind": m.kind, "line": m.lineno,
                "before": m.before[:160], "after": m.after[:160],
                "rc": rc, "verdict": verdict,
            })
            flag = "  " if verdict == "CAUGHT" else "<<"
            print(f"{flag} [{i:3d}/{len(mutants)}] {verdict:9s} {m.kind:10s} L{m.lineno:<4d} "
                  f"{m.before[:70]!r} -> {m.after[:70]!r}", flush=True)
    finally:
        restore()

    rc_after = run_suite()
    if rc_after != 0:
        print(f"!! restore left the tree red (rc={rc_after}) — results unusable")
        return 2

    caught = sum(1 for r in results if r["verdict"] == "CAUGHT")
    survived = [r for r in results if r["verdict"] == "SURVIVED"]
    print(f"\n=== {caught}/{len(results)} CAUGHT · {len(survived)} SURVIVED ===")
    for r in survived:
        print(f"  SURVIVED {r['kind']:10s} L{r['line']:<4d} {r['before'][:80]!r} -> {r['after'][:80]!r}")

    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({
        "target": args.target, "tests": args.tests, "full_suite": args.full_suite,
        "total": len(results), "caught": caught, "survived": len(survived),
        "results": results,
    }, indent=2))
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
